### ISSUE TITLE
Register profile to Supermarket

### ISSUE THREAD

**Issue by chris-rock** [sliim-cookbooks/tests-chef-client-hardening#1]
Hi @Sliim Great work, it would be really cool if the profile would be available via supermarket: https://supermarket.chef.io/tools?type=compliance_profile What do you think?

**Comment by Sliim** [comment]
Hi @chris-rock Thanks :)
Yes, you are right :+1:  I add it immediately!

**Comment by Sliim** [comment]
Done! https://supermarket.chef.io/tools/chef-client-hardening ;)

**Comment by chris-rock** [comment]
Awesome. Thanks @sliim
